# Implement Periodic Condition
Guorui Shen, guorui233@outlook.com

We consider a periodic dataset $u(t)\in R^Q, t=1, 2, \cdots, L$, which is sampled from $u = u(x, t)$. This is constantly occuring in  the numerical solution to a PDE. $u(t)\in R^Q$ can be divided into $g$ groups with each group of length $q$ if $g\cdot q=Q$.

In [1]:
import numpy as np

In [2]:
a = np.arange(180.0)
num_x = 18
num_t = len(a)/num_x
u = a[:num_x].reshape((-1, 1))
for i in range(1, num_t):
    u = np.hstack((u, a[i*num_x:(i+1)*num_x].reshape(-1, 1)))
print(u)

[[  0.  18.  36.  54.  72.  90. 108. 126. 144. 162.]
 [  1.  19.  37.  55.  73.  91. 109. 127. 145. 163.]
 [  2.  20.  38.  56.  74.  92. 110. 128. 146. 164.]
 [  3.  21.  39.  57.  75.  93. 111. 129. 147. 165.]
 [  4.  22.  40.  58.  76.  94. 112. 130. 148. 166.]
 [  5.  23.  41.  59.  77.  95. 113. 131. 149. 167.]
 [  6.  24.  42.  60.  78.  96. 114. 132. 150. 168.]
 [  7.  25.  43.  61.  79.  97. 115. 133. 151. 169.]
 [  8.  26.  44.  62.  80.  98. 116. 134. 152. 170.]
 [  9.  27.  45.  63.  81.  99. 117. 135. 153. 171.]
 [ 10.  28.  46.  64.  82. 100. 118. 136. 154. 172.]
 [ 11.  29.  47.  65.  83. 101. 119. 137. 155. 173.]
 [ 12.  30.  48.  66.  84. 102. 120. 138. 156. 174.]
 [ 13.  31.  49.  67.  85. 103. 121. 139. 157. 175.]
 [ 14.  32.  50.  68.  86. 104. 122. 140. 158. 176.]
 [ 15.  33.  51.  69.  87. 105. 123. 141. 159. 177.]
 [ 16.  34.  52.  70.  88. 106. 124. 142. 160. 178.]
 [ 17.  35.  53.  71.  89. 107. 125. 143. 161. 179.]]


In [3]:
Q = len(u)
q = 6
g = Q/q
l = 1
print(Q)

in_dim, out_dim = q+2*l, q
in_data = np.empty((0, in_dim))
out_data = np.empty((0, out_dim))

18


In [4]:
# # Non-periodic condition
# for k in range(g):
#     if k==0:
#         index = range(q+2*l)
#     elif k==g-1:
#         index = range(Q-q-2*l, Q)
#     else:
#         index = range(k*q-l, (k+1)*q+l)
    
#     for i in range(num_t-1):
#         in_data = np.vstack((in_data, u[index, i]))
#         out_data = np.vstack((out_data, u[k*q:(k+1)*q, i+1]))

In [5]:
# Periodic condition
for k in range(g):
    if k==0:
        index = range(-l, 0)+range(q+l)
    elif k==g-1:
        index = range(Q-q-l, Q)+range(l)
    else:
        index = range(k*q-l, (k+1)*q+l)
    
    for i in range(num_t-1):
        in_data = np.vstack((in_data, u[index, i]))
        out_data = np.vstack((out_data, u[k*q:(k+1)*q, i+1]))

In [6]:
for j in range(len(in_data)):
    print('From', in_data[j], 'to', out_data[j])

('From', array([17.,  0.,  1.,  2.,  3.,  4.,  5.,  6.]), 'to', array([18., 19., 20., 21., 22., 23.]))
('From', array([35., 18., 19., 20., 21., 22., 23., 24.]), 'to', array([36., 37., 38., 39., 40., 41.]))
('From', array([53., 36., 37., 38., 39., 40., 41., 42.]), 'to', array([54., 55., 56., 57., 58., 59.]))
('From', array([71., 54., 55., 56., 57., 58., 59., 60.]), 'to', array([72., 73., 74., 75., 76., 77.]))
('From', array([89., 72., 73., 74., 75., 76., 77., 78.]), 'to', array([90., 91., 92., 93., 94., 95.]))
('From', array([107.,  90.,  91.,  92.,  93.,  94.,  95.,  96.]), 'to', array([108., 109., 110., 111., 112., 113.]))
('From', array([125., 108., 109., 110., 111., 112., 113., 114.]), 'to', array([126., 127., 128., 129., 130., 131.]))
('From', array([143., 126., 127., 128., 129., 130., 131., 132.]), 'to', array([144., 145., 146., 147., 148., 149.]))
('From', array([161., 144., 145., 146., 147., 148., 149., 150.]), 'to', array([162., 163., 164., 165., 166., 167.]))
('From', array([ 